hero_names = ("Adela",
                                "Adelaide",
                                "Adrienne",
                                "Aenain",
                                "Aeris",
                                "Agar",
                                "Aine",
                                "Aislinn",
                                "Ajit",
                                "Alagar",
                                "Alamar",
                                "Alkin",
                                "Anabel",
                                "Andal",
                                "Andra",
                                "Arlach",
                                "Ash",
                                "Astra",
                                "Astral",
                                "Axsis",
                                "Ayden",
                                "Beatrice",
                                "Bertram",
                                "Bidley",
                                "Boragus",
                                "Brissa",
                                "Broghild",
                                "Bron",
                                "Caitlin",
                                "Calh",
                                "Calid",
                                "Casmetra",
                                "Cassiopeia",
                                "Catherine",
                                "Celestine",
                                "Charna",
                                "Christian",
                                "Ciele",
                                "Clancy",
                                "Clavius",
                                "Corkes",
                                "Coronius",
                                "Crag Hack",
                                "Cuthbert",
                                "Cyra",
                                "Dace",
                                "Damacon",
                                "Daremyth",
                                "Dargem",
                                "Darkstorn",
                                "Deemer",
                                "Derek",
                                "Dessa",
                                "Dracon",
                                "Drakon",
                                "Dury",
                                "Eanswythe",
                                "Edric",
                                "Elleshar",
                                "Elmore",
                                "Eovacius",
                                "Erdamon",
                                "Fafner",
                                "Fiona",
                                "Fiur",
                                "Floribert",
                                "Frederick",
                                "Galthran",
                                "Gelare",
                                "Gelu",
                                "Gem",
                                "Geon",
                                "Gerwulf",
                                "Gird",
                                "Giselle",
                                "Gretchin",
                                "Grindan",
                                "Gundula",
                                "Gunnar",
                                "Gurnisson",
                                "Haart Lich",
                                "Halon",
                                "Henrietta",
                                "Ignatius",
                                "Ignissa",
                                "Illor",
                                "Ingham",
                                "Inteus",
                                "Iona",
                                "Isra",
                                "Ivor",
                                "Jabarkas",
                                "Jaegar",
                                "Jeddite",
                                "Jenova",
                                "Jeremy",
                                "Josephine",
                                "Kalt",
                                "Kilgor",
                                "Kinkeria",
                                "Korbac",
                                "Krellion",
                                "Kyrre",
                                "Labetha",
                                "Lacus",
                                "Leena",
                                "Lord Haart",
                                "Lorelei",
                                "Loynis",
                                "Luna",
                                "Malcom",
                                "Malekith",
                                "Manfred",
                                "Marius",
                                "Melchior",
                                "Melodia",
                                "Mephala",
                                "Merist",
                                "Miriam",
                                "Mirlanda",
                                "Moandor",
                                "Monere",
                                "Morton",
                                "Murdoch",
                                "Mutare",
                                "Mutare Drake",
                                "Nagash",
                                "Neela",
                                "Nimbus",
                                "Nymus",
                                "Octavia",
                                "Olema",
                                "Oris",
                                "Orrin",
                                "Pasis",
                                "Piquedram",
                                "Pyre",
                                "Ranloo",
                                "Rashka",
                                "Rion",
                                "Rissa",
                                "Roland",
                                "Rosic",
                                "Ryland",
                                "Sam",
                                "Sandro",
                                "Sanya",
                                "Saurug",
                                "Sephinroth",
                                "Septienna",
                                "Serena",
                                "Shakti",
                                "Shiva",
                                "Sir Mullich",
                                "Solmyr",
                                "Sorsha",
                                "Spint",
                                "Straker",
                                "Styg",
                                "Sylvia",
                                "Synca",
                                "Tamika",
                                "Tancred",
                                "Tark",
                                "Tavin",
                                "Tazar",
                                "Terek",
                                "Thane",
                                "Thant",
                                "Theodorus",
                                "Thorgrim",
                                "Thunar",
                                "Tiva",
                                "Todd",
                                "Torosar",
                                "Tyraxor",
                                "Tyris",
                                "Ufretin",
                                "Uland",
                                "Valeska",
                                "Verdish",
                                "Vey",
                                "Victoria",
                                "Vidomina",
                                "Vokial",
                                "Voy",
                                "Wrathmont",
                                "Wynona",
                                "Wystan",
                                "Xarfax",
                                "Xeron",
                                "Xsi",
                                "Xyron",
                                "Yog",
                                "Zilare",
                                "Ziph",
                                "Zubin",
                                "Zydar")
skill_ids = {
    'Air Magic': 15,
    'Archery': 1,
    'Armorer': 23,
    'Artillery': 20,
    'Ballistics': 10,
    'Diplomacy': 4,
    'Eagle Eye': 11,
    'Earth Magic': 17,
    'Estates': 13,
    'Fire Magic': 14,
    'First Aid': 27,
    'Intelligence': 24,
    'Interference': 28,
    'Leadership': 6,
    'Learning': 21,
    'Logistics': 2,
    'Luck': 9,
    'Mysticism': 8,
    'Navigation': 5,
    'Necromancy': 12,
    'Offense': 22,
    'Pathfinding': 0,
    'Resistance': 26,
    'Scholar': 18,
    'Scouting': 3,
    'Sorcery': 25,
    'Tactics': 19,
    'Water Magic': 16,
    'Wisdom': 7,
}

hero_ids = ('Orrin', 'Valeska', 'Edric', 'Sylvia', 'Lord Haart', 'Sorsha', 'Christian', 'Tyris', 'Rion', 'Adela', 'Cuthbert', 'Adelaide', 'Ingham', 'Sanya', 'Loynis', 'Caitlin', 'Mephala', 'Ufretin', 'Jenova', 'Ryland', 'Thorgrim', 'Ivor', 'Clancy', 'Kyrre', 'Coronius', 'Uland', 'Elleshar', 'Gem', 'Malcom', 'Melodia', 'Alagar', 'Aeris', 'Piquedram', 'Thane', 'Josephine', 'Neela', 'Torosar ', 'Fafner', 'Rissa', 'Iona', 'Astral', 'Halon', 'Serena', 'Daremyth', 'Theodorus', 'Solmyr', 'Cyra', 'Aine', 'Fiona', 'Rashka', 'Marius', 'Ignatius', 'Octavia', 'Calh', 'Pyre', 'Nymus', 'Ayden', 'Xyron', 'Axsis', 'Olema', 'Calid', 'Ash', 'Zydar', 'Xarfax', 'Straker', 'Vokial', 'Moandor', 'Charna', 'Tamika', 'Isra', 'Clavius', 'Galthran', 'Septienna', 'Aislinn', 'Sandro', 'Nimbus', 'Thant', 'Xsi', 'Vidomina', 'Nagash', 'Lorelei', 'Arlach', 'Dace', 'Ajit', 'Damacon', 'Gunnar', 'Synca', 'Shakti', 'Alamar', 'Jaegar', 'Malekith', 'Jeddite', 'Geon', 'Deemer', 'Sephinroth', 'Darkstorn', 'Yog', 'Gurnisson', 'Jabarkas', 'Shiva', 'Gretchin', 'Krellion', 'Crag Hack', 'Tyraxor', 'Gird', 'Vey', 'Dessa', 'Terek', 'Zubin', 'Gundula', 'Oris', 'Saurug', 'Bron', 'Drakon', 'Wystan', 'Tazar', 'Alkin', 'Korbac', 'Gerwulf', 'Broghild', 'Mirlanda', 'Rosic', 'Voy', 'Verdish', 'Merist', 'Styg', 'Andra', 'Tiva', 'Pasis', 'Thunar', 'Ignissa', 'Lacus', 'Monere', 'Erdamon', 'Fiur', 'Kalt', 'Luna', 'Brissa', 'Ciele', 'Labetha', 'Inteus', 'Aenain', 'Gelare', 'Grindan', 'Sir Mullich', 'Adrienne', 'Catherine', 'Dracon', 'Gelu', 'Kilgor', 'Haart Lich', 'Mutare', 'Roland', 'Mutare Drake', 'Boragus', 'Xeron', 'Corkes', 'Jeremy', 'Illor', 'Derek', 'Leena', 'Anabel', 'Cassiopeia', 'Miriam', 'Casmetra', 'Eovacius', 'Spint', 'Andal', 'Manfred', 'Zilare', 'Astra', 'Dargem', 'Bidley', 'Tark', 'Elmore', 'Beatrice', 'Kinkeria', 'Ranloo', 'Giselle', 'Henrietta', 'Sam', 'Tancred', 'Melchior', 'Floribert', 'Wynona', 'Dury', 'Morton', 'Celestine', 'Todd', 'Agar', 'Bertram', 'Wrathmont', 'Ziph', 'Victoria', 'Eanswythe', 'Frederick', 'Tavin', 'Murdoch')

skill_names = {y: x for x, y in skill_ids.items()}

primary_skills = 1107
secondary_skill_count = 222
secondary_skills = 166
affiliation = -1

player_color = -204
player_hero_count = player_color + 1
player_heroes = player_color + 8
player_resources = -48


