hero_names = ("Adela",
                                "Adelaide",
                                "Adrienne",
                                "Aenain",
                                "Aeris",
                                "Agar",
                                "Aine",
                                "Aislinn",
                                "Ajit",
                                "Alagar",
                                "Alamar",
                                "Alkin",
                                "Anabel",
                                "Andal",
                                "Andra",
                                "Arlach",
                                "Ash",
                                "Astra",
                                "Astral",
                                "Axsis",
                                "Ayden",
                                "Beatrice",
                                "Bertram",
                                "Bidley",
                                "Boragus",
                                "Brissa",
                                "Broghild",
                                "Bron",
                                "Caitlin",
                                "Calh",
                                "Calid",
                                "Casmetra",
                                "Cassiopeia",
                                "Catherine",
                                "Celestine",
                                "Charna",
                                "Christian",
                                "Ciele",
                                "Clancy",
                                "Clavius",
                                "Corkes",
                                "Coronius",
                                "Crag Hack",
                                "Cuthbert",
                                "Cyra",
                                "Dace",
                                "Damacon",
                                "Daremyth",
                                "Dargem",
                                "Darkstorn",
                                "Deemer",
                                "Derek",
                                "Dessa",
                                "Dracon",
                                "Drakon",
                                "Dury",
                                "Eanswythe",
                                "Edric",
                                "Elleshar",
                                "Elmore",
                                "Eovacius",
                                "Erdamon",
                                "Fafner",
                                "Fiona",
                                "Fiur",
                                "Floribert",
                                "Frederick",
                                "Galthran",
                                "Gelare",
                                "Gelu",
                                "Gem",
                                "Geon",
                                "Gerwulf",
                                "Gird",
                                "Giselle",
                                "Gretchin",
                                "Grindan",
                                "Gundula",
                                "Gunnar",
                                "Gurnisson",
                                "Haart Lich",
                                "Halon",
                                "Henrietta",
                                "Ignatius",
                                "Ignissa",
                                "Illor",
                                "Ingham",
                                "Inteus",
                                "Iona",
                                "Isra",
                                "Ivor",
                                "Jabarkas",
                                "Jaegar",
                                "Jeddite",
                                "Jenova",
                                "Jeremy",
                                "Josephine",
                                "Kalt",
                                "Kilgor",
                                "Kinkeria",
                                "Korbac",
                                "Krellion",
                                "Kyrre",
                                "Labetha",
                                "Lacus",
                                "Leena",
                                "Lord Haart",
                                "Lorelei",
                                "Loynis",
                                "Luna",
                                "Malcom",
                                "Malekith",
                                "Manfred",
                                "Marius",
                                "Melchior",
                                "Melodia",
                                "Mephala",
                                "Merist",
                                "Miriam",
                                "Mirlanda",
                                "Moandor",
                                "Monere",
                                "Morton",
                                "Murdoch",
                                "Mutare",
                                "Mutare Drake",
                                "Nagash",
                                "Neela",
                                "Nimbus",
                                "Nymus",
                                "Octavia",
                                "Olema",
                                "Oris",
                                "Orrin",
                                "Pasis",
                                "Piquedram",
                                "Pyre",
                                "Ranloo",
                                "Rashka",
                                "Rion",
                                "Rissa",
                                "Roland",
                                "Rosic",
                                "Ryland",
                                "Sam",
                                "Sandro",
                                "Sanya",
                                "Saurug",
                                "Sephinroth",
                                "Septienna",
                                "Serena",
                                "Shakti",
                                "Shiva",
                                "Sir Mullich",
                                "Solmyr",
                                "Sorsha",
                                "Spint",
                                "Straker",
                                "Styg",
                                "Sylvia",
                                "Synca",
                                "Tamika",
                                "Tancred",
                                "Tark",
                                "Tavin",
                                "Tazar",
                                "Terek",
                                "Thane",
                                "Thant",
                                "Theodorus",
                                "Thorgrim",
                                "Thunar",
                                "Tiva",
                                "Todd",
                                "Torosar",
                                "Tyraxor",
                                "Tyris",
                                "Ufretin",
                                "Uland",
                                "Valeska",
                                "Verdish",
                                "Vey",
                                "Victoria",
                                "Vidomina",
                                "Vokial",
                                "Voy",
                                "Wrathmont",
                                "Wynona",
                                "Wystan",
                                "Xarfax",
                                "Xeron",
                                "Xsi",
                                "Xyron",
                                "Yog",
                                "Zilare",
                                "Ziph",
                                "Zubin",
                                "Zydar")
skill_ids = {
    'Air Magic': 15,
    'Archery': 1,
    'Armorer': 23,
    'Artillery': 20,
    'Ballistics': 10,
    'Diplomacy': 4,
    'Eagle Eye': 11,
    'Earth Magic': 17,
    'Estates': 13,
    'Fire Magic': 14,
    'First Aid': 27,
    'Intelligence': 24,
    'Interference': 28,
    'Leadership': 6,
    'Learning': 21,
    'Logistics': 2,
    'Luck': 9,
    'Mysticism': 8,
    'Navigation': 5,
    'Necromancy': 12,
    'Offense': 22,
    'Pathfinding': 0,
    'Resistance': 26,
    'Scholar': 18,
    'Scouting': 3,
    'Sorcery': 25,
    'Tactics': 19,
    'Water Magic': 16,
    'Wisdom': 7,
}

skill_names = {y: x for x, y in skill_ids.items()}

secondary_skill_count = 222
secondary_skills = 166
affiliation = -1

